services:

  odoo:
    image: odoo:18
    container_name: odooo
    ports:
      - "8069:8069"
    depends_on:
      - db
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
      - ADMIN_PASSWORD=admin
    volumes:
      - odoo_volumen:/var/lib/odoo

  db:
    image: postgres:16
    container_name: odo_db
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_DB=postgres
    volumes:
      - db_volumen:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    depends_on:
      - db
    environment:
      - PGADMIN_DEFAULT_EMAIL=drodrigueztato@danielcastelao.org
      - PGADMIN_DEFAULT_PASSWORD=Vboxuser1.
    ports:
      - "8081:80"

volumes:
  odoo_volumen:
  db_volumen:
